// react-legacy/components/AddWorkout.tsx

import React, { useState, useMemo } from 'react';
import { Exercise } from '../types';
import { exerciseLibrary, ExerciseInfo } from '../data/exerciseLibrary';
import { ChevronLeftIcon, DumbbellIcon, SearchIcon, PlusIcon, MinusIcon, XIcon, VideoIcon, PlusCircleIcon } from './Icons';

interface AddWorkoutProps {
    onAddWorkout: (workout: { notes?: string; perceivedExertion: number; exercises: Exercise[] }) => void;
    onBack: () => void;
}

type ExerciseDetails = Omit<Exercise, 'id' | 'name' | 'instructions' | 'videoLink' | 'isPR'>;

const FilterButton: React.FC<{ label: string; isActive: boolean; onClick: () => void; }> = ({ label, isActive, onClick }) => (
    <button
        onClick={onClick}
        className={`px-3 py-1.5 text-xs font-semibold rounded-full transition-colors flex-shrink-0 whitespace-nowrap ${
            isActive ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-accent'
        }`}
    >
        {label}
    </button>
);

const WorkoutExerciseCard: React.FC<{
    exercise: ExerciseInfo;
    details: ExerciseDetails;
    onDetailChange: (id: string, field: keyof ExerciseDetails, value: any) => void;
    onRemove: (id: string) => void;
}> = ({ exercise, details, onDetailChange, onRemove }) => {
    return (
        <div className="bg-muted p-4 rounded-lg">
            <div className="flex justify-between items-start">
                <div>
                    <p className="font-bold text-md">{exercise.name}</p>
                    <p className="text-xs text-muted-foreground">{exercise.muscleGroup}</p>
                </div>
                <button onClick={() => onRemove(exercise.id)} className="p-1 text-muted-foreground hover:text-destructive">
                    <XIcon className="w-4 h-4" />
                </button>
            </div>
            <div className="grid grid-cols-3 gap-3 mt-4">
                <div>
                    <label className="block text-xs font-medium text-muted-foreground mb-1">Sets</label>
                    <input type="number" value={details.sets} onChange={e => onDetailChange(exercise.id, 'sets', Number(e.target.value))} className="w-full bg-background border-input rounded-md px-2 py-1.5 focus:outline-none focus:ring-1 focus:ring-ring text-sm" />
                </div>
                 <div>
                    <label className="block text-xs font-medium text-muted-foreground mb-1">Reps</label>
                    <input type="text" value={details.reps} onChange={e => onDetailChange(exercise.id, 'reps', e.target.value)} className="w-full bg-background border-input rounded-md px-2 py-1.5 focus:outline-none focus:ring-1 focus:ring-ring text-sm" />
                </div>
                 <div>
                    <label className="block text-xs font-medium text-muted-foreground mb-1">Weight (kg)</label>
                    <input type="number" value={details.weight} onChange={e => onDetailChange(exercise.id, 'weight', Number(e.target.value))} className="w-full bg-background border-input rounded-md px-2 py-1.5 focus:outline-none focus:ring-1 focus:ring-ring text-sm" />
                </div>
            </div>
        </div>
    );
};


export const AddWorkout: React.FC<AddWorkoutProps> = ({ onAddWorkout, onBack }) => {
    const [searchQuery, setSearchQuery] = useState('');
    const [selectedExercises, setSelectedExercises] = useState<ExerciseInfo[]>([]);
    const [exerciseDetails, setExerciseDetails] = useState<Record<string, ExerciseDetails>>({});
    const [workoutNotes, setWorkoutNotes] = useState('');
    const [workoutRPE, setWorkoutRPE] = useState(7);
    
    const equipmentFilters = ['all', 'none', 'minimal', 'gym'] as const;
    type EquipmentFilter = typeof equipmentFilters[number];
    const muscleFilters = ['all', 'Chest', 'Back', 'Legs', 'Shoulders', 'Biceps', 'Triceps', 'Abs', 'Full Body', 'Cardio', 'Other'] as const;
    type MuscleFilter = typeof muscleFilters[number];

    const [selectedEquipment, setSelectedEquipment] = useState<EquipmentFilter>('all');
    const [selectedMuscleGroup, setSelectedMuscleGroup] = useState<MuscleFilter>('all');

    const addExercise = (exercise: ExerciseInfo) => {
        if (selectedExercises.some(e => e.id === exercise.id)) return;
        
        setSelectedExercises(prev => [...prev, exercise]);
        setExerciseDetails(prev => ({
            ...prev,
            [exercise.id]: { sets: 3, reps: '10', weight: 0 }
        }));
    };
    
    const removeExercise = (exerciseId: string) => {
        setSelectedExercises(prev => prev.filter(e => e.id !== exerciseId));
        const newDetails = {...exerciseDetails};
        delete newDetails[exerciseId];
        setExerciseDetails(newDetails);
    };

    const handleDetailChange = (id: string, field: keyof ExerciseDetails, value: any) => {
        setExerciseDetails(prev => ({
            ...prev,
            [id]: { ...prev[id], [field]: value }
        }));
    };

    const handleSaveWorkout = () => {
        const timestamp = Date.now();
        const finalExercises: Exercise[] = selectedExercises.map((info, index) => ({
            id: `${info.id}_${timestamp}_${index}`,
            name: info.name,
            videoLink: info.videoLink,
            instructions: info.instructions,
            ...exerciseDetails[info.id]
        }));
        
        onAddWorkout({
            notes: workoutNotes,
            exercises: finalExercises,
            perceivedExertion: workoutRPE,
        });
    };

    const filteredLibrary = useMemo(() => {
        return exerciseLibrary.filter(ex => {
            const matchesQuery = ex.name.toLowerCase().includes(searchQuery.toLowerCase());
            const matchesEquipment = selectedEquipment === 'all' || ex.equipment === selectedEquipment;
            const matchesMuscle = selectedMuscleGroup === 'all' || ex.muscleGroup === selectedMuscleGroup;
            return matchesQuery && matchesEquipment && matchesMuscle;
        });
    }, [searchQuery, selectedEquipment, selectedMuscleGroup]);
    
    return (
        <div className="flex flex-col h-full bg-background">
             <header className="p-4 border-b border-border sticky top-0 bg-background/80 backdrop-blur-sm z-20">
                <div className="relative text-center">
                    <button onClick={onBack} className="absolute left-0 top-1/2 -translate-y-1/2 p-1">
                        <ChevronLeftIcon className="w-6 h-6" />
                    </button>
                    <h1 className="text-lg font-semibold">Log Workout</h1>
                </div>
            </header>
            <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
                {/* Left Panel: Current Workout */}
                <div className="w-full lg:w-1/2 xl:w-2/5 border-b lg:border-b-0 lg:border-r border-border flex flex-col">
                    <h2 className="text-lg font-semibold p-4">Current Workout ({selectedExercises.length})</h2>
                    <div className="flex-1 overflow-y-auto p-4 space-y-3">
                        {selectedExercises.length > 0 ? (
                             selectedExercises.map(ex => (
                                <WorkoutExerciseCard 
                                    key={ex.id}
                                    exercise={ex}
                                    details={exerciseDetails[ex.id]}
                                    onDetailChange={handleDetailChange}
                                    onRemove={removeExercise}
                                />
                             ))
                        ) : (
                            <div className="text-center text-muted-foreground pt-10">
                                <DumbbellIcon className="w-12 h-12 mx-auto" />
                                <p className="mt-2 font-semibold">Add exercises from the library</p>
                                <p className="text-sm">Find and add exercises to build your workout.</p>
                            </div>
                        )}
                    </div>
                    <div className="p-4 border-t border-border space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-muted-foreground mb-1">Workout Notes</label>
                            <textarea value={workoutNotes} onChange={e => setWorkoutNotes(e.target.value)} rows={2} className="w-full bg-muted border-input rounded-md px-3 py-2" placeholder="How did the session feel?"></textarea>
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-muted-foreground mb-1">Perceived Exertion (RPE): {workoutRPE}/10</label>
                             <input type="range" min="1" max="10" value={workoutRPE} onChange={e => setWorkoutRPE(Number(e.target.value))} className="w-full" />
                        </div>
                        <button onClick={handleSaveWorkout} disabled={selectedExercises.length === 0} className="w-full bg-primary text-primary-foreground font-semibold py-3 rounded-lg disabled:opacity-50">
                            Save Workout
                        </button>
                    </div>
                </div>

                {/* Right Panel: Exercise Library */}
                 <div className="w-full lg:w-1/2 xl:w-3/5 flex flex-col">
                    <div className="p-4 border-b border-border sticky top-0 bg-background z-10">
                        <div className="relative">
                            <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                            <input type="text" placeholder="Search exercises..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} className="w-full bg-muted border-input rounded-md pl-10 pr-4 py-2" />
                        </div>
                         <div className="mt-3">
                            <p className="text-xs font-semibold mb-2 text-muted-foreground">Equipment</p>
                            <div className="flex space-x-2 overflow-x-auto pb-1 -mb-1">
                                {equipmentFilters.map(e => <FilterButton key={e} label={e.charAt(0).toUpperCase() + e.slice(1)} isActive={selectedEquipment === e} onClick={() => setSelectedEquipment(e)} />)}
                            </div>
                        </div>
                         <div className="mt-3">
                            <p className="text-xs font-semibold mb-2 text-muted-foreground">Muscle Group</p>
                            <div className="flex space-x-2 overflow-x-auto pb-1 -mb-1">
                                {muscleFilters.map(m => <FilterButton key={m} label={m} isActive={selectedMuscleGroup === m} onClick={() => setSelectedMuscleGroup(m)} />)}
                            </div>
                        </div>
                    </div>
                     <div className="flex-1 overflow-y-auto p-4">
                        <ul className="space-y-2">
                             {filteredLibrary.map(exercise => {
                                const isAdded = selectedExercises.some(e => e.id === exercise.id);
                                return (
                                <li key={exercise.id} className="bg-muted p-3 rounded-lg flex items-center justify-between">
                                    <div>
                                        <p className="font-semibold">{exercise.name}</p>
                                        <div className="flex items-center space-x-2 mt-1">
                                            <span className="text-xs px-2 py-0.5 bg-background rounded-full">{exercise.muscleGroup}</span>
                                            {exercise.videoLink && <a href={exercise.videoLink} target="_blank" rel="noopener noreferrer"><VideoIcon className="w-4 h-4 text-primary"/></a>}
                                        </div>
                                    </div>
                                    <button onClick={() => isAdded ? removeExercise(exercise.id) : addExercise(exercise)} className={`p-2 rounded-full transition-colors ${isAdded ? 'bg-destructive/20 text-destructive' : 'bg-primary/20 text-primary'}`}>
                                        {isAdded ? <MinusIcon className="w-4 h-4"/> : <PlusIcon className="w-4 h-4"/>}
                                    </button>
                                </li>
                            )})}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    );
};

// src/components/AddWorkout.vue
<template>
  <div class="space-y-6 pb-6">
    <!-- Header -->
    <div class="pt-6 px-6">
      <h1 class="text-3xl font-bold">Start a Workout</h1>
      <p class="text-muted-foreground">Log your exercises and track your progress</p>
    </div>

    <div class="px-6 space-y-6">
      <!-- Exercise Search & Add Section -->
      <Card>
        <div class="p-4 border-b border-border">
          <h2 class="text-lg font-semibold mb-4">Add Exercises</h2>

          <div class="space-y-4">
            <!-- Search/Select Exercise -->
            <div>
              <label class="text-sm font-medium text-muted-foreground mb-2 block">Exercise Name</label>
              <input v-model="exerciseSearch" type="text" placeholder="Search exercises..."
                class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground placeholder-muted-foreground" />
              <div v-if="filteredExerciseLibrary.length > 0"
                class="mt-2 border border-border rounded-lg max-h-48 overflow-y-auto">
                <button v-for="exercise in filteredExerciseLibrary" :key="exercise" @click="selectExercise(exercise)"
                  class="w-full text-left px-3 py-2 hover:bg-muted focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary transition-colors text-sm">
                  {{ exercise }}
                </button>
              </div>
            </div>

            <!-- Exercise Details Form -->
            <div v-if="currentExerciseData.name" class="space-y-4 pt-4 border-t border-border">
              <div class="grid grid-cols-2 gap-4">
                <!-- Sets -->
                <div>
                  <label class="text-sm font-medium text-muted-foreground mb-2 block">Sets</label>
                  <input v-model.number="currentExerciseData.sets" type="number" min="1" max="10"
                    class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground" />
                </div>

                <!-- Reps -->
                <div>
                  <label class="text-sm font-medium text-muted-foreground mb-2 block">Reps</label>
                  <input v-model="currentExerciseData.reps" type="text" placeholder="e.g., 8-12, 5, AMRAP"
                    class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground" />
                </div>
              </div>

              <!-- Weight -->
              <div>
                <label class="text-sm font-medium text-muted-foreground mb-2 block">Weight (kg) - Optional</label>
                <input v-model.number="currentExerciseData.weight" type="number" placeholder="0.0" step="0.5"
                  class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground" />
              </div>

              <!-- PR Indicator -->
              <label class="flex items-center gap-2 cursor-pointer">
                <input v-model="currentExerciseData.isPR" type="checkbox" class="w-4 h-4 rounded border-border" />
                <span class="text-sm font-medium">Personal Record (PR) ⭐</span>
              </label>

              <!-- Notes -->
              <div>
                <label class="text-sm font-medium text-muted-foreground mb-2 block">Exercise Notes - Optional</label>
                <textarea v-model="currentExerciseData.instructions" placeholder="How did it feel? Any form cues?"
                  rows="2"
                  class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground placeholder-muted-foreground resize-none" />
              </div>

              <!-- Add Exercise Button -->
              <button @click="addExercise"
                class="w-full px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors font-medium">
                Add Exercise
              </button>
            </div>
          </div>
        </div>
      </Card>

      <!-- Added Exercises List -->
      <Card v-if="addedExercises.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Exercises in This Workout ({{ addedExercises.length }})</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="(exercise, index) in addedExercises" :key="index" class="p-4">
            <div class="flex items-start justify-between mb-2">
              <div>
                <p class="font-semibold">{{ exercise.name }}</p>
                <p class="text-sm text-muted-foreground">
                  {{ exercise.sets }} sets × {{ exercise.reps }}
                  <span v-if="exercise.weight">@ {{ exercise.weight }}kg</span>
                  <span v-if="exercise.isPR" class="ml-2 text-xs bg-warning/10 text-warning px-1.5 py-0.5 rounded">
                    PR ⭐
                  </span>
                </p>
              </div>
              <button @click="removeExercise(index)"
                class="text-destructive hover:bg-destructive/10 px-2 py-1 rounded text-xs focus:outline-none focus:ring-2 focus:ring-destructive focus:ring-offset-1 transition-colors">
                Remove
              </button>
            </div>
            <div v-if="exercise.instructions" class="text-xs text-muted-foreground mt-2 italic">
              {{ exercise.instructions }}
            </div>
          </div>
        </div>
      </Card>

      <!-- Workout Notes Section -->
      <Card>
        <div class="p-4 border-b border-border">
          <h2 class="text-lg font-semibold mb-4">Workout Details</h2>

          <!-- Perceived Exertion Slider -->
          <div class="mb-6">
            <div class="flex items-center justify-between mb-3">
              <label class="text-sm font-medium">Perceived Exertion</label>
              <span class="text-lg font-semibold text-primary">{{ perceivedExertion }}/10</span>
            </div>
            <input v-model.number="perceivedExertion" type="range" min="0" max="10" step="1"
              class="w-full h-2 bg-muted rounded-lg appearance-none cursor-pointer" />
            <div class="flex justify-between text-xs text-muted-foreground mt-2">
              <span>Easy</span>
              <span>Moderate</span>
              <span>Maximum</span>
            </div>
          </div>

          <!-- Workout Notes -->
          <div>
            <label class="text-sm font-medium text-muted-foreground mb-2 block">Workout Notes</label>
            <textarea v-model="workoutNotes" placeholder="Overall notes about the workout..." rows="3"
              class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground placeholder-muted-foreground resize-none" />
          </div>
        </div>
      </Card>

      <!-- Completion Toggle & Submit -->
      <Card>
        <div class="p-4">
          <label class="flex items-center gap-3 cursor-pointer mb-4">
            <input v-model="isCompleted" type="checkbox" class="w-4 h-4 rounded border-border" />
            <span class="text-sm font-medium">Mark workout as completed</span>
          </label>

          <div class="flex gap-3">
            <button @click="$emit('back')"
              class="flex-1 px-4 py-2.5 border border-border rounded-lg hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors font-medium">
              Cancel
            </button>
            <button @click="submitWorkout" :disabled="addedExercises.length === 0" :class="[
              'flex-1 px-4 py-2.5 rounded-lg font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-1 border',
              addedExercises.length === 0
                ? 'bg-muted text-muted-foreground cursor-not-allowed border-muted'
                : 'bg-success text-success-foreground hover:bg-success/90 focus:ring-success border-success'
            ]">
              Save Workout
            </button>
          </div>
        </div>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Exercise } from '@/types';
import { computed, ref } from 'vue';
import Card from './common/Card.vue';

const emit = defineEmits<{
  addWorkout: [workoutData: { notes?: string; perceivedExertion: number; exercises: Exercise[] }];
  back: [];
}>();

// Exercise library
const exerciseLibrary = [
  'Bench Press',
  'Barbell Squat',
  'Deadlift',
  'Pull-ups',
  'Dumbbell Row',
  'Leg Press',
  'Chest Fly',
  'Lat Pulldown',
  'Leg Curl',
  'Leg Extension',
  'Shoulder Press',
  'Lateral Raise',
  'Bicep Curl',
  'Tricep Dip',
  'Push-ups',
  'Planks',
  'Running',
  'Cycling',
  'Swimming',
  'Rowing',
];

// State
const exerciseSearch = ref('');
const currentExerciseData = ref<Partial<Exercise>>({
  sets: 3,
  reps: '8-12',
});
const addedExercises = ref<Exercise[]>([]);
const perceivedExertion = ref(5);
const workoutNotes = ref('');
const isCompleted = ref(false);

// Computed
const filteredExerciseLibrary = computed(() => {
  const search = exerciseSearch.value.toLowerCase();
  if (!search) return [];
  return exerciseLibrary.filter(e => e.toLowerCase().includes(search)).slice(0, 8);
});

// Methods
const selectExercise = (exerciseName: string) => {
  currentExerciseData.value.name = exerciseName;
  exerciseSearch.value = '';
};

const addExercise = () => {
  if (!currentExerciseData.value.name) return;

  const exercise: Exercise = {
    id: `exercise_${Date.now()}`,
    name: currentExerciseData.value.name,
    sets: currentExerciseData.value.sets || 3,
    reps: currentExerciseData.value.reps || '8-12',
    weight: currentExerciseData.value.weight,
    instructions: currentExerciseData.value.instructions,
    isPR: currentExerciseData.value.isPR,
  };

  addedExercises.value.push(exercise);

  // Reset form
  currentExerciseData.value = { sets: 3, reps: '8-12' };
  exerciseSearch.value = '';
};

const removeExercise = (index: number) => {
  addedExercises.value.splice(index, 1);
};

const submitWorkout = () => {
  if (addedExercises.value.length === 0) return;

  const workoutData = {
    notes: workoutNotes.value,
    perceivedExertion: perceivedExertion.value,
    exercises: addedExercises.value,
  };

  emit('addWorkout', workoutData);
};
</script>
