// react-legacy/components/Goals.tsx


import React, { useState } from 'react';
import { User, Goal, GoalStatus } from '../types';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from './common/Card';
import { PlusCircleIcon, TargetIcon, CheckCircle2Icon } from './Icons';
import { format, parseISO, differenceInDays } from 'date-fns';
import { NewGoalModal } from './NewGoalModal';
import { WeeklyCheckinModal } from './WeeklyCheckinModal';
import { EmptyState } from './common/EmptyState';

interface GoalsProps {
  currentUser: User;
  goals: Goal[];
  onAddNewGoal: (goalData: Omit<Goal, 'id' | 'userId' | 'current' | 'status'>) => void;
  onBulkUpdateGoals: (updates: { goalId: string; newCurrent: number }[]) => void;
}

const GoalCard: React.FC<{goal: Goal}> = ({ goal }) => {
    const progress = Math.min(100, Math.round((goal.current / goal.target) * 100));
    const daysLeft = differenceInDays(parseISO(goal.dueDate), new Date());
    const isCompleted = goal.status === GoalStatus.COMPLETED;

    return (
        <Card className={`${isCompleted ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800' : ''}`}>
            <CardHeader>
                <div className="flex items-center justify-between">
                     <CardTitle className="text-md">{goal.title}</CardTitle>
                     {isCompleted && <CheckCircle2Icon className="w-6 h-6 text-green-500" />}
                </div>
            </CardHeader>
            <CardContent>
                 <div className="flex justify-between items-baseline mb-1">
                    <span className="font-semibold text-sm">{goal.current}{goal.metric} / {goal.target}{goal.metric}</span>
                    <span className="text-xs text-muted-foreground font-medium">{progress}%</span>
                  </div>
                  <div className="w-full bg-muted rounded-full h-2.5">
                    <div className={`${isCompleted ? 'bg-green-500' : 'bg-primary dark:bg-primary-dark'} h-2.5 rounded-full`} style={{ width: `${progress}%` }}></div>
                  </div>
            </CardContent>
            {!isCompleted && (
                <CardFooter>
                     <p className="text-xs text-muted-foreground">
                        {daysLeft > 0 ? `${daysLeft} days left` : 'Due today'} - Due on {format(parseISO(goal.dueDate), 'MMM d')}
                    </p>
                </CardFooter>
            )}
        </Card>
    );
}

export const Goals: React.FC<GoalsProps> = ({ currentUser, goals, onAddNewGoal, onBulkUpdateGoals }) => {
  const [isGoalModalOpen, setIsGoalModalOpen] = useState(false);
  const [isCheckinModalOpen, setIsCheckinModalOpen] = useState(false);

  const activeGoals = goals.filter(g => g.userId === currentUser.id && g.status === GoalStatus.ACTIVE);
  const completedGoals = goals.filter(g => g.userId === currentUser.id && g.status === GoalStatus.COMPLETED);

  return (
    <>
    <div className="p-4 md:p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
            <h1 className="text-2xl md:text-3xl font-bold text-foreground">Goals</h1>
            <p className="text-muted-foreground">Track your progress and stay motivated.</p>
        </div>
        <button onClick={() => setIsGoalModalOpen(true)} className="flex items-center space-x-2 bg-primary text-primary-foreground px-4 py-2 rounded-lg font-semibold text-sm hover:bg-primary/90">
            <PlusCircleIcon className="w-5 h-5"/>
            <span>Set New Goal</span>
        </button>
      </div>
      
      <Card>
        <CardHeader>
            <CardTitle>Weekly Check-in</CardTitle>
        </CardHeader>
        <CardContent>
            <p className="text-sm text-muted-foreground mb-4">Update your progress and reflect on your week to stay on track with your goals.</p>
            <button onClick={() => setIsCheckinModalOpen(true)} className="w-full md:w-auto bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary-dark font-semibold py-2 px-4 rounded-lg">
                Complete Weekly Check-in
            </button>
        </CardContent>
      </Card>

      <div>
        <h2 className="text-xl font-semibold mb-4 flex items-center space-x-2"><TargetIcon className="w-5 h-5"/> <span>Active Goals</span></h2>
        {activeGoals.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {activeGoals.map(goal => <GoalCard key={goal.id} goal={goal} />)}
            </div>
        ) : (
            <Card>
              <CardContent>
                <EmptyState 
                    icon={<TargetIcon />}
                    title="No Active Goals"
                    message="Set a new goal to start tracking your progress."
                    action={{ label: "Set New Goal", onClick: () => setIsGoalModalOpen(true) }}
                />
              </CardContent>
            </Card>
        )}
      </div>

       <div>
        <h2 className="text-xl font-semibold mb-4 flex items-center space-x-2"><CheckCircle2Icon className="w-5 h-5"/> <span>Completed Goals</span></h2>
        {completedGoals.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {completedGoals.map(goal => <GoalCard key={goal.id} goal={goal} />)}
            </div>
        ) : (
             <Card>
              <CardContent>
                 <EmptyState 
                    icon={<CheckCircle2Icon />}
                    title="No Completed Goals"
                    message="Keep working towards your active goals to see them here."
                />
              </CardContent>
            </Card>
        )}
      </div>

    </div>
    <NewGoalModal isOpen={isGoalModalOpen} onClose={() => setIsGoalModalOpen(false)} onSetGoal={onAddNewGoal} />
    <WeeklyCheckinModal isOpen={isCheckinModalOpen} onClose={() => setIsCheckinModalOpen(false)} activeGoals={activeGoals} onUpdateGoals={onBulkUpdateGoals} />
    </>
  );
};

// src/components/Goals.vue
<template>
  <div class="space-y-6 pb-6">
    <!-- Header -->
    <div class="pt-6 px-6 flex items-center justify-between">
      <div>
        <h1 class="text-3xl font-bold">Goals</h1>
        <p class="text-muted-foreground">Track your fitness objectives</p>
      </div>
      <button @click="showNewGoalModal = true"
        class="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 transition-colors">
        <TargetIcon class="w-5 h-5" />
        New Goal
      </button>
    </div>

    <div class="px-6 space-y-6">
      <!-- Goal Stats -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <div class="p-4">
            <p class="text-sm text-muted-foreground mb-2">Total Goals</p>
            <p class="text-3xl font-bold">{{ userGoals.length }}</p>
          </div>
        </Card>
        <Card>
          <div class="p-4">
            <p class="text-sm text-muted-foreground mb-2">Active</p>
            <p class="text-3xl font-bold text-primary">{{ activeGoals.length }}</p>
          </div>
        </Card>
        <Card>
          <div class="p-4">
            <p class="text-sm text-muted-foreground mb-2">Completed</p>
            <p class="text-3xl font-bold text-success">{{ completedGoals.length }}</p>
          </div>
        </Card>
      </div>

      <!-- Active Goals -->
      <Card v-if="activeGoals.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Active Goals</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="goal in activeGoals" :key="goal.id" class="p-4 hover:bg-muted/50 transition-colors">
            <div class="space-y-3">
              <!-- Goal Header -->
              <div class="flex items-start justify-between">
                <div class="flex-1">
                  <h3 class="font-semibold text-lg">{{ goal.title }}</h3>
                  <p class="text-sm text-muted-foreground">
                    Due {{ formatDueDate(goal.dueDate) }}
                  </p>
                </div>
                <span :class="[
                  'px-3 py-1 rounded text-xs font-medium',
                  goalProgressPercent(goal) >= 100
                    ? 'bg-success/10 text-success'
                    : goalProgressPercent(goal) >= 50
                      ? 'bg-info/10 text-info'
                      : 'bg-warning/10 text-warning'
                ]">
                  {{ goalProgressPercent(goal) }}%
                </span>
              </div>

              <!-- Progress Bar -->
              <div class="space-y-1">
                <div class="flex items-center justify-between text-sm">
                  <span class="text-muted-foreground">{{ goal.current }} / {{ goal.target }} {{ goal.metric }}</span>
                  <span class="font-medium">{{ ((goal.current / goal.target) * 100).toFixed(0) }}%</span>
                </div>
                <div class="w-full bg-muted rounded-full h-3">
                  <div class="bg-gradient-to-r from-info to-primary h-3 rounded-full transition-all duration-300"
                    :style="{ width: `${Math.min((goal.current / goal.target) * 100, 100)}%` }" />
                </div>
              </div>

              <!-- Update Current Value -->
              <div class="flex gap-2 pt-2">
                <input v-model.number="goalUpdates[goal.id]" type="number"
                  :placeholder="`Update: current is ${goal.current}`"
                  class="flex-1 px-3 py-2 text-sm rounded-lg border border-border bg-background text-foreground" />
                <button @click="updateGoalValue(goal.id)"
                  class="px-4 py-2 bg-primary text-primary-foreground text-sm rounded-lg hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors">
                  Update
                </button>
              </div>
            </div>
          </div>
        </div>
      </Card>

      <!-- Completed Goals -->
      <Card v-if="completedGoals.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Completed Goals 🎉</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="goal in completedGoals" :key="goal.id" class="p-4">
            <div class="flex items-start justify-between">
              <div>
                <h3 class="font-semibold text-lg">{{ goal.title }}</h3>
                <p class="text-sm text-muted-foreground">
                  {{ goal.current }} {{ goal.metric }} · Completed
                </p>
              </div>
              <span class="bg-success/10 text-success px-3 py-1 rounded text-xs font-medium">
                ✓ Completed
              </span>
            </div>
          </div>
        </div>
      </Card>

      <!-- Archived Goals -->
      <Card v-if="archivedGoals.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Archived Goals</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="goal in archivedGoals" :key="goal.id" class="p-4 opacity-60">
            <div class="flex items-start justify-between">
              <div>
                <h3 class="font-semibold text-lg">{{ goal.title }}</h3>
                <p class="text-sm text-muted-foreground">
                  {{ goal.current }} {{ goal.metric }}
                </p>
              </div>
              <span class="bg-muted text-muted-foreground px-3 py-1 rounded text-xs font-medium">
                Archived
              </span>
            </div>
          </div>
        </div>
      </Card>

      <!-- Empty State -->
      <EmptyState v-if="userGoals.length === 0" title="No Goals Yet"
        message="Set your first fitness goal to get started!" />
    </div>

    <!-- New Goal Modal -->
    <Modal v-model="showNewGoalModal" title="New Goal">
      <div class="p-6 max-w-md w-full">
        <h2 class="text-2xl font-bold mb-4">Create New Goal</h2>

        <form @submit.prevent="submitNewGoal" class="space-y-4">
          <!-- Goal Title -->
          <div>
            <label class="text-sm font-medium text-muted-foreground mb-2 block">Goal Title</label>
            <input v-model="newGoal.title" type="text" placeholder="e.g., Bench Press 100kg"
              class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground" required />
          </div>

          <!-- Target Value -->
          <div>
            <label class="text-sm font-medium text-muted-foreground mb-2 block">Target Value</label>
            <input v-model.number="newGoal.target" type="number" placeholder="100"
              class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground" required />
          </div>

          <!-- Metric -->
          <div>
            <label class="text-sm font-medium text-muted-foreground mb-2 block">Metric</label>
            <select v-model="newGoal.metric"
              class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground" required>
              <option value="kg">Kilograms (kg)</option>
              <option value="reps">Reps</option>
              <option value="cm">Centimeters (cm)</option>
              <option value="mins">Minutes</option>
              <option value="%">Percentage (%)</option>
            </select>
          </div>

          <!-- Due Date -->
          <div>
            <label class="text-sm font-medium text-muted-foreground mb-2 block">Due Date</label>
            <input v-model="newGoal.dueDate" type="date"
              class="w-full px-3 py-2 rounded-lg border border-border bg-background text-foreground" required />
          </div>

          <!-- Buttons -->
          <div class="flex gap-3 pt-4">
            <button type="button" @click="showNewGoalModal = false"
              class="flex-1 px-4 py-2 border border-border rounded-lg hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors">
              Cancel
            </button>
            <button type="submit"
              class="flex-1 px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors">
              Create Goal
            </button>
          </div>
        </form>
      </div>
    </Modal>
  </div>
</template>

<script setup lang="ts">
import type { Goal, User } from '@/types';
import { GoalStatus } from '@/types';
import { formatDistanceToNow, parseISO } from 'date-fns';
import { computed, ref } from 'vue';
import Card from './common/Card.vue';
import EmptyState from './common/EmptyState.vue';
import Modal from './common/Modal.vue';
import TargetIcon from './icons/TargetIcon.vue';

const props = defineProps<{
  currentUser: User;
  goals: Goal[];
}>();

// State
const showNewGoalModal = ref(false);
const goalUpdates = ref<Record<string, number>>({});
const newGoal = ref({
  title: '',
  target: 0,
  metric: 'kg' as const,
  dueDate: '',
});

// Computed
const userGoals = computed(() =>
  props.goals.filter(g => g.userId === props.currentUser.id)
);

const activeGoals = computed(() =>
  userGoals.value.filter(g => g.status === GoalStatus.ACTIVE)
);

const completedGoals = computed(() =>
  userGoals.value.filter(g => g.status === GoalStatus.COMPLETED)
);

const archivedGoals = computed(() =>
  userGoals.value.filter(g => g.status === GoalStatus.ARCHIVED)
);

// Methods
const formatDueDate = (dateString: string) => {
  try {
    return formatDistanceToNow(parseISO(dateString), { addSuffix: true });
  } catch {
    return dateString;
  }
};

const goalProgressPercent = (goal: Goal) => {
  return Math.min(Math.round((goal.current / goal.target) * 100), 100);
};

const updateGoalValue = (goalId: string) => {
  const newValue = goalUpdates.value[goalId];
  if (newValue === undefined) return;

  emit('bulkUpdateGoals', [
    {
      goalId,
      newCurrent: newValue,
    },
  ]);

  goalUpdates.value[goalId] = undefined!;
};

const submitNewGoal = () => {
  if (!newGoal.value.title || !newGoal.value.target || !newGoal.value.dueDate) return;

  emit('addNewGoal', {
    title: newGoal.value.title,
    target: newGoal.value.target,
    metric: newGoal.value.metric,
    dueDate: newGoal.value.dueDate,
  });

  // Reset form
  newGoal.value = {
    title: '',
    target: 0,
    metric: 'kg',
    dueDate: '',
  };

  showNewGoalModal.value = false;
};

const emit = defineEmits<{
  addNewGoal: [goalData: any];
  bulkUpdateGoals: [updates: any[]];
}>();
</script>
