// src/pages/ChatView.vue
<template>
  <div class="space-y-6 pb-6">
    <!-- Header -->
    <div class="pt-6 px-6">
      <h1 class="text-3xl font-bold">Messages</h1>
      <p class="text-muted-foreground">{{ chat.name || 'Direct message' }}</p>
    </div>

    <div class="px-6 space-y-4 flex flex-col h-[calc(100vh-12rem)]">
      <!-- Messages Container -->
      <div class="flex-1 overflow-y-auto space-y-3 mb-4">
        <div v-if="sortedMessages.length === 0" class="h-full flex items-center justify-center">
          <EmptyState title="No Messages Yet" message="Start the conversation!" />
        </div>
        <div v-for="message in sortedMessages" :key="message.id" :class="[
          'flex',
          message.senderId === currentUser.id ? 'justify-end' : 'justify-start'
        ]">
          <div :class="[
            'max-w-sm px-4 py-2 rounded-lg',
            message.senderId === currentUser.id
              ? 'bg-primary text-primary-foreground rounded-br-none'
              : 'bg-muted text-muted-foreground rounded-bl-none'
          ]">
            <p class="text-sm">{{ message.text }}</p>
            <p class="text-xs opacity-70 mt-1">{{ formatMessageTime(message.createdAt) }}</p>
          </div>
        </div>
      </div>

      <!-- Message Input -->
      <Card>
        <div class="p-4 space-y-2">
          <form @submit.prevent="sendMessageHandler" class="flex gap-2">
            <input v-model="messageInput" type="text" placeholder="Type a message..."
              class="flex-1 px-3 py-2 rounded-lg border border-border bg-background text-foreground placeholder-muted-foreground" />
            <button type="submit"
              class="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors font-medium">
              Send
            </button>
          </form>
        </div>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import Card from '@/components/common/Card.vue';
import EmptyState from '@/components/common/EmptyState.vue';
import { useUserStore } from '@/stores/user';
import type { Chat, Message } from '@/types';
import { formatDistanceToNow, parseISO } from 'date-fns';
import { computed, onMounted, ref } from 'vue';

const userStore = useUserStore();
const currentUser = computed(() => userStore.currentUser);

// TODO: Replace with actual API calls
const chat = ref<Chat | null>(null);
const messages = ref<Message[]>([]);

// TODO: Replace with actual API calls
const sendMessageAPI = async (chatObj: Chat, text: string) => {
  console.log('TODO: Send message:', text, 'to chat:', chatObj.id);
};

const markAsReadAPI = async (chatId: string) => {
  console.log('TODO: Mark chat as read:', chatId);
};

// State
const messageInput = ref('');

// Computed
const sortedMessages = computed(() =>
  messages.value
    .filter(m => m.chatId === chat.value?.id)
    .sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime())
);

// Methods
const formatMessageTime = (dateString: string) => {
  try {
    return formatDistanceToNow(parseISO(dateString), { addSuffix: true });
  } catch {
    return dateString;
  }
};

const sendMessageHandler = () => {
  if (!messageInput.value.trim() || !chat.value) return;
  sendMessageAPI(chat.value, messageInput.value);
  messageInput.value = '';
};

// Mark as read on mount
onMounted(() => {
  if (chat.value) {
    markAsReadAPI(chat.value.id);
  }
});
</script>

// react-legacy/components/ChatView.tsx


import React, { useState, useRef, useEffect } from 'react';
import { Message, User, Chat } from '../types';
import { users } from '../data/mockData';
import { format, parseISO } from 'date-fns';
import { PaperclipIcon, SendIcon, PinIcon } from './Icons';

interface ChatViewProps {
  chat: Chat;
  messages: Message[];
  currentUser: User;
  onSendMessage: (text: string) => void;
  onMarkAsRead: () => void;
}

const MessageBubble: React.FC<{ message: Message; isOwnMessage: boolean; sender?: User }> = ({ message, isOwnMessage, sender }) => {
  return (
    <div className={`flex items-end gap-2 ${isOwnMessage ? 'justify-end' : 'justify-start'}`}>
      {!isOwnMessage && (
        <img src={sender?.avatar} alt={sender?.name} className="w-8 h-8 rounded-full" />
      )}
      <div className={`max-w-xs md:max-w-md p-3 rounded-2xl ${isOwnMessage ? 'bg-primary text-primary-foreground rounded-br-lg' : 'bg-muted dark:bg-muted text-foreground rounded-bl-lg'}`}>
        {!isOwnMessage && <p className="text-xs font-bold text-primary dark:text-primary-dark mb-1">{sender?.name}</p>}
        <p className="text-sm whitespace-pre-wrap">{message.text}</p>
        <p className="text-xs opacity-70 mt-1 text-right">{format(parseISO(message.createdAt), 'p')}</p>
      </div>
    </div>
  );
};

export const ChatView: React.FC<ChatViewProps> = ({ chat, messages, currentUser, onSendMessage, onMarkAsRead }) => {
  const [newMessage, setNewMessage] = useState('');
  const messagesEndRef = useRef<null | HTMLDivElement>(null);

  const pinnedMessages = messages.filter(m => m.pinned);
  const regularMessages = messages.filter(m => !m.pinned);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    onMarkAsRead();
  }, [chat.id, onMarkAsRead]);

  useEffect(scrollToBottom, [messages]);
  
  const handleSendMessage = (e: React.FormEvent) => {
    e.preventDefault();
    if (newMessage.trim() === '') return;
    onSendMessage(newMessage);
    setNewMessage('');
  };

  const getChatTitle = () => {
    if (chat.name) return chat.name;
    const otherParticipantId = chat.participants.find(p => p !== currentUser.id);
    const otherParticipant = users.find(u => u.id === otherParticipantId);
    return otherParticipant?.name || 'Chat';
  };

  return (
    <div className="flex flex-col h-full bg-card">
      <header className="p-4 border-b border-border flex items-center">
        <h2 className="text-lg font-semibold">{getChatTitle()}</h2>
      </header>
      <main className="flex-1 overflow-y-auto">
        {pinnedMessages.length > 0 && (
            <div className="p-4 sticky top-0 bg-card/80 backdrop-blur-sm">
                <div className="bg-amber-100 dark:bg-amber-900/30 border border-amber-300 dark:border-amber-800 rounded-lg p-3">
                    {pinnedMessages.map(message => (
                        <div key={message.id} className="flex items-start space-x-2 text-amber-800 dark:text-amber-200">
                             <PinIcon className="w-4 h-4 mt-0.5 flex-shrink-0" />
                             <p className="text-sm">{message.text}</p>
                        </div>
                    ))}
                </div>
            </div>
        )}
        <div className="p-4 space-y-4">
            {regularMessages.map(message => {
            const sender = users.find(u => u.id === message.senderId);
            return (
                <MessageBubble
                key={message.id}
                message={message}
                isOwnMessage={message.senderId === currentUser.id}
                sender={sender}
                />
            );
            })}
            <div ref={messagesEndRef} />
        </div>
      </main>
      <footer className="p-4 border-t border-border">
        <form onSubmit={handleSendMessage} className="flex items-center space-x-2">
          <button type="button" className="p-2 text-muted-foreground hover:text-primary">
            <PaperclipIcon className="w-5 h-5"/>
          </button>
          <input
            type="text"
            value={newMessage}
            onChange={(e) => setNewMessage(e.target.value)}
            placeholder="Type a message..."
            className="flex-1 bg-muted border-input rounded-full px-4 py-2 focus:outline-none focus:ring-2 focus:ring-ring"
          />
          <button type="submit" className="p-3 bg-primary text-primary-foreground rounded-full hover:bg-primary/90 disabled:opacity-50" disabled={!newMessage.trim()}>
            <SendIcon className="w-5 h-5"/>
          </button>
        </form>
      </footer>
    </div>
  );
};
