// src/components/ClientHome.vue
<template>
  <div class="space-y-6 pb-6">
    <!-- Header -->
    <div class="pt-6 px-6">
      <h1 class="text-3xl font-bold">Welcome back, {{ currentUser.name }}! 👋</h1>
      <p class="text-muted-foreground">Here's your fitness overview</p>
    </div>

    <div class="px-6 space-y-6">
      <!-- Summary Statistics -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <!-- Workouts This Week -->
        <Card>
          <div class="p-4">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm text-muted-foreground">Workouts This Week</p>
                <p class="text-2xl font-bold">{{ workoutsThisWeek }}</p>
              </div>
              <DumbbellIcon class="w-8 h-8 text-primary opacity-60" />
            </div>
          </div>
        </Card>

        <!-- Total Workouts -->
        <Card>
          <div class="p-4">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm text-muted-foreground">Total Workouts</p>
                <p class="text-2xl font-bold">{{ workouts.length }}</p>
              </div>
              <TrendingUpIcon class="w-8 h-8 text-success opacity-60" />
            </div>
          </div>
        </Card>

        <!-- Active Goals -->
        <Card>
          <div class="p-4">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm text-muted-foreground">Active Goals</p>
                <p class="text-2xl font-bold">{{ activeGoalsCount }}</p>
              </div>
              <TargetIcon class="w-8 h-8 text-warning opacity-60" />
            </div>
          </div>
        </Card>

        <!-- Current Streak -->
        <Card>
          <div class="p-4">
            <div class="flex items-center justify-between">
              <div>
                <p class="text-sm text-muted-foreground">Best Habit Streak</p>
                <p class="text-2xl font-bold">{{ bestStreak }}</p>
              </div>
              <TrendingUpIcon class="w-8 h-8 text-info opacity-60" />
            </div>
          </div>
        </Card>
      </div>

      <!-- Recent Workouts -->
      <Card v-if="recentWorkouts.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Recent Workouts</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="workout in recentWorkouts" :key="workout.id" class="p-4 hover:bg-muted/50 transition-colors">
            <div class="flex items-start justify-between">
              <div class="flex-1">
                <p class="font-medium">{{ formatDate(workout.date) }}</p>
                <p class="text-sm text-muted-foreground">{{ workout.exercises.length }} exercises</p>
                <div class="mt-2 flex flex-wrap gap-1">
                  <span v-for="exercise in workout.exercises.slice(0, 3)" :key="exercise.id"
                    class="text-xs bg-muted text-muted-foreground px-2 py-1 rounded">
                    {{ exercise.name }}
                  </span>
                  <span v-if="workout.exercises.length > 3" class="text-xs text-muted-foreground px-2 py-1">
                    +{{ workout.exercises.length - 3 }} more
                  </span>
                </div>
              </div>
              <div class="text-right">
                <p class="text-sm">Exertion: {{ workout.perceivedExertion }}/10</p>
                <span :class="[
                  'mt-2 inline-block px-2 py-1 rounded text-xs font-medium',
                  workout.completed
                    ? 'bg-success/10 text-success'
                    : 'bg-muted text-muted-foreground'
                ]">
                  {{ workout.completed ? 'Completed' : 'In Progress' }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </Card>

      <EmptyState v-else title="No Workouts Yet" message="Start your first workout to see them here!" />

      <!-- Goal Progress -->
      <Card v-if="goals.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Goal Progress</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="goal in activeGoals" :key="goal.id" class="p-4">
            <div class="flex items-center justify-between mb-2">
              <h3 class="font-medium">{{ goal.title }}</h3>
              <span class="text-sm text-muted-foreground">{{ goal.current }} / {{ goal.target }} {{ goal.metric
              }}</span>
            </div>
            <div class="w-full bg-muted rounded-full h-2">
              <div class="bg-primary h-2 rounded-full transition-all duration-300"
                :style="{ width: `${Math.min((goal.current / goal.target) * 100, 100)}%` }" />
            </div>
            <p class="text-xs text-muted-foreground mt-2">
              {{ goalProgress(goal) }}% complete · Due {{ formatDate(goal.dueDate) }}
            </p>
          </div>
        </div>
      </Card>

      <!-- Habit Tracker -->
      <Card v-if="habits.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Habit Tracker</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="habit in habits" :key="habit.id" class="p-4">
            <div class="flex items-center justify-between mb-3">
              <div>
                <h3 class="font-medium">{{ habit.name }}</h3>
                <p class="text-xs text-muted-foreground">{{ habit.frequency }}</p>
              </div>
              <div class="text-right">
                <p class="font-semibold text-success">{{ habit.streak }} day streak 🔥</p>
                <p class="text-xs text-muted-foreground">{{ habit.current }} / {{ habit.target }} {{ habit.unit }}</p>
              </div>
            </div>
            <div class="w-full bg-muted rounded-full h-2">
              <div class="bg-success h-2 rounded-full transition-all duration-300"
                :style="{ width: `${Math.min((habit.current / habit.target) * 100, 100)}%` }" />
            </div>
          </div>
        </div>
      </Card>

      <!-- Quick Actions -->
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <button @click="$emit('goToAddWorkout')"
          class="p-4 rounded-lg border border-primary bg-primary/10 hover:bg-primary/20 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors text-center"
          aria-label="Log a workout">
          <DumbbellIcon class="w-6 h-6 mx-auto mb-2 text-primary" />
          <p class="font-medium text-sm">Log Workout</p>
        </button>
        <button
          class="p-4 rounded-lg border border-muted hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors text-center"
          aria-label="Log nutrition intake">
          <AppleIcon class="w-6 h-6 mx-auto mb-2 text-warning" />
          <p class="font-medium text-sm">Log Nutrition</p>
        </button>
        <button
          class="p-4 rounded-lg border border-muted hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors text-center"
          aria-label="View schedule">
          <CalendarIcon class="w-6 h-6 mx-auto mb-2 text-info" />
          <p class="font-medium text-sm">Schedule</p>
        </button>
        <button
          class="p-4 rounded-lg border border-muted hover:bg-muted focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1 transition-colors text-center"
          aria-label="View progress">
          <TrendingUpIcon class="w-6 h-6 mx-auto mb-2 text-success" />
          <p class="font-medium text-sm">Progress</p>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Goal, Habit, Measurement, Session, User, Workout } from '@/types';
import { GoalStatus } from '@/types';
import { formatDistanceToNow, isThisWeek, parseISO } from 'date-fns';
import { computed } from 'vue';
import Card from './common/Card.vue';
import EmptyState from './common/EmptyState.vue';
import AppleIcon from './icons/AppleIcon.vue';
import CalendarIcon from './icons/CalendarIcon.vue';
import DumbbellIcon from './icons/DumbbellIcon.vue';
import TargetIcon from './icons/TargetIcon.vue';
import TrendingUpIcon from './icons/TrendingUpIcon.vue';

const props = defineProps<{
  currentUser: User;
  sessions: Session[];
  goals: Goal[];
  habits: Habit[];
  workouts: Workout[];
  measurements: Measurement[];
}>();

const emit = defineEmits<{
  addMeasurement: [measurement: Omit<Measurement, 'id' | 'userId' | 'date'>];
  updateGoal: [goalId: string, newCurrent: number];
  addNutritionLog: [log: any];
  goToAddWorkout: [];
}>();

// Computed properties
const recentWorkouts = computed(() =>
  props.workouts
    .filter(w => w.userId === props.currentUser.id)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 5)
);

const workoutsThisWeek = computed(() =>
  props.workouts.filter(w => w.userId === props.currentUser.id && isThisWeek(parseISO(w.date))).length
);

const activeGoals = computed(() =>
  props.goals.filter(g => g.userId === props.currentUser.id && g.status === GoalStatus.ACTIVE)
);

const activeGoalsCount = computed(() => activeGoals.value.length);

const bestStreak = computed(() => {
  if (props.habits.length === 0) return 0;
  return Math.max(...props.habits.filter(h => h.userId === props.currentUser.id).map(h => h.streak));
});

// Helper functions
const formatDate = (dateString: string) => {
  try {
    return formatDistanceToNow(parseISO(dateString), { addSuffix: true });
  } catch {
    return dateString;
  }
};

const goalProgress = (goal: Goal) => {
  return Math.min(Math.round((goal.current / goal.target) * 100), 100);
};
</script>

// react-legacy/components/ClientHome.tsx

import React, { useState } from 'react';
import { User, Session, Goal, Habit, Workout, Measurement, GoalStatus, Exercise, Screen } from '../types';
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from './common/Card';
import { AppleIcon, CheckCircle2Icon, ChevronRightIcon, DumbbellIcon, FlameIcon, FootprintsIcon, BedDoubleIcon, DropletsIcon, PlusCircleIcon, TargetIcon, TrophyIcon } from './Icons';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { format, parseISO } from 'date-fns';
import { Modal } from './common/Modal';
import { LogNutritionModal } from './LogNutritionModal';

// --- Prop Types ---
interface ClientHomeProps {
  currentUser: User;
  sessions: Session[];
  goals: Goal[];
  habits: Habit[];
  workouts: Workout[];
  measurements: Measurement[];
  onAddMeasurement: (measurement: Omit<Measurement, 'id' | 'userId' | 'date'>) => void;
  onUpdateGoal: (goalId: string, newCurrent: number) => void;
  onAddNutritionLog: (log: { type: 'meal' | 'snack' | 'water'; description?: string; protein?: number; waterAmount?: number }) => void;
  onGoToAddWorkout: () => void;
}

// --- Helper & Sub-components ---
const HabitIcon: React.FC<{ name: Habit['name'], className?: string }> = ({ name, className }) => {
  switch (name) {
    case 'Protein': return <FlameIcon className={className} />;
    case 'Water': return <DropletsIcon className={className} />;
    case 'Steps': return <FootprintsIcon className={className} />;
    case 'Sleep': return <BedDoubleIcon className={className} />;
    default: return null;
  }
};

const QuickLogButton: React.FC<{ icon: React.ReactNode, label: string, onClick: () => void }> = ({ icon, label, onClick }) => (
    <button onClick={onClick} className="flex flex-col items-center justify-center space-y-2 text-center group">
        <div className="w-16 h-16 bg-primary/10 text-primary dark:bg-primary/20 dark:text-primary-dark rounded-full flex items-center justify-center transition-transform group-hover:scale-110">
            {icon}
        </div>
        <span className="text-xs font-medium text-muted-foreground">{label}</span>
    </button>
);

const FormInput: React.FC<React.InputHTMLAttributes<HTMLInputElement> & {label: string}> = ({label, ...props}) => (
    <div>
        <label className="block text-sm font-medium text-muted-foreground mb-1">{label}</label>
        <input {...props} className="w-full bg-muted border-input rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-ring" />
    </div>
);

const FormButton: React.FC<{children: React.ReactNode, onClick: () => void}> = ({ children, onClick }) => (
    <button onClick={onClick} className="w-full bg-primary text-primary-foreground font-semibold py-2.5 px-4 rounded-lg text-sm hover:bg-primary/90 transition-colors">
        {children}
    </button>
);

// --- Main Component ---
export const ClientHome: React.FC<ClientHomeProps> = ({ 
    currentUser, sessions, goals, habits, workouts, measurements, 
    onAddMeasurement, onUpdateGoal, onAddNutritionLog, onGoToAddWorkout
}) => {
  
  type ModalType = 'nutrition' | 'goal' | 'measurement';
  const [activeModal, setActiveModal] = useState<ModalType | null>(null);

  // --- Form States ---
  const [goalId, setGoalId] = useState('');
  const [goalCurrent, setGoalCurrent] = useState(0);
  const [bodyweight, setBodyweight] = useState(0);

  const activeGoals = goals.filter(g => g.userId === currentUser.id && g.status === GoalStatus.ACTIVE);
  
  // --- Submit Handlers ---
  const handleUpdateGoal = () => {
    if (goalId) onUpdateGoal(goalId, goalCurrent);
    setGoalId(''); setGoalCurrent(0);
    setActiveModal(null);
  }
  const handleAddMeasurement = () => {
    onAddMeasurement({ bodyweight });
    setBodyweight(0);
    setActiveModal(null);
  }

  // --- Data for Charts & Cards ---
  const today = new Date().toISOString().split('T')[0];
  const upcomingSession = sessions.find(s => s.date.startsWith(today) && s.attendees.includes(currentUser.id));
  const recentPRs = workouts
    .filter(w => w.userId === currentUser.id)
    .flatMap(w => w.exercises)
    .filter(e => e.isPR)
    .slice(0, 2);

  const weightData = measurements
    .filter(m => m.userId === currentUser.id && m.bodyweight)
    .map(m => ({
        date: format(parseISO(m.date), 'MMM d'),
        weight: m.bodyweight
    }));

  return (
    <>
    <div className="space-y-6 p-4 md:p-6">
      <h1 className="text-2xl md:text-3xl font-bold text-foreground">
        Hello, {currentUser.name.split(' ')[0]}!
      </h1>
      
      {upcomingSession && (
        <Card className="bg-primary text-primary-foreground dark:bg-primary-dark dark:text-background">
          <CardContent className="flex items-center justify-between">
            <div>
              <p className="font-semibold">{upcomingSession.title}</p>
              <p className="text-sm opacity-80">
                {format(parseISO(upcomingSession.date), 'p')} - {upcomingSession.location}
              </p>
            </div>
            <ChevronRightIcon className="w-6 h-6" />
          </CardContent>
        </Card>
      )}

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <QuickLogButton icon={<DumbbellIcon className="w-8 h-8"/>} label="Log Workout" onClick={onGoToAddWorkout}/>
        <QuickLogButton icon={<AppleIcon className="w-8 h-8"/>} label="Log Meal" onClick={() => setActiveModal('nutrition')}/>
        <QuickLogButton icon={<TargetIcon className="w-8 h-8"/>} label="Update Goal" onClick={() => setActiveModal('goal')}/>
        <QuickLogButton icon={<PlusCircleIcon className="w-8 h-8"/>} label="Add Measurement" onClick={() => setActiveModal('measurement')}/>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Daily Habits</CardTitle>
          <CardDescription>Keep up the great work!</CardDescription>
        </CardHeader>
        <CardContent className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {habits.filter(h => h.userId === currentUser.id).map(habit => (
             <div key={habit.id} className="flex items-center space-x-3 bg-muted p-3 rounded-lg">
                <div className="p-2 bg-background rounded-full">
                    <HabitIcon name={habit.name} className="w-6 h-6 text-primary dark:text-primary-dark" />
                </div>
                <div>
                    <p className="font-semibold text-sm">{habit.name}</p>
                    <p className="text-xs text-muted-foreground">{habit.current} / {habit.target} {habit.unit}</p>
                </div>
             </div>
          ))}
        </CardContent>
      </Card>
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Active Goals</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {goals.filter(g => g.userId === currentUser.id && g.status === 'ACTIVE').map(goal => {
              const progress = Math.min(100, Math.round((goal.current / goal.target) * 100));
              return (
                <div key={goal.id}>
                  <div className="flex justify-between items-baseline mb-1">
                    <span className="font-medium text-sm">{goal.title}</span>
                    <span className="text-xs text-muted-foreground">{goal.current}{goal.metric} / {goal.target}{goal.metric}</span>
                  </div>
                  <div className="w-full bg-muted rounded-full h-2.5">
                    <div className="bg-primary dark:bg-primary-dark h-2.5 rounded-full" style={{ width: `${progress}%` }}></div>
                  </div>
                </div>
              );
            })}
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>Recent PRs</CardTitle>
          </CardHeader>
          <CardContent>
            {recentPRs.length > 0 ? (
                <ul className="space-y-3">
                    {recentPRs.map(pr => (
                        <li key={pr.id} className="flex items-center space-x-3">
                            <TrophyIcon className="w-5 h-5 text-amber-500" />
                            <p className="text-sm font-medium">{pr.name}: <span className="text-primary dark:text-primary-dark font-semibold">{pr.weight}kg</span> for {pr.reps} reps</p>
                        </li>
                    ))}
                </ul>
            ) : (
                <p className="text-sm text-muted-foreground">No recent PRs. Keep pushing!</p>
            )}
          </CardContent>
        </Card>
      </div>

       <Card>
        <CardHeader>
            <CardTitle>Bodyweight Trend</CardTitle>
            <CardDescription>Last 30 days</CardDescription>
        </CardHeader>
        <CardContent className="h-64">
             <ResponsiveContainer width="100%" height="100%">
                <LineChart data={weightData} margin={{ top: 5, right: 20, left: -10, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                    <XAxis dataKey="date" stroke="hsl(var(--muted-foreground))" fontSize={12} />
                    <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} domain={['dataMin - 2', 'dataMax + 2']}/>
                    <Tooltip contentStyle={{
                        backgroundColor: 'hsl(var(--card))',
                        borderColor: 'hsl(var(--border))'
                    }}/>
                    <Line type="monotone" dataKey="weight" stroke="hsl(var(--primary))" strokeWidth={2} dot={{ r: 4 }} activeDot={{ r: 6 }} />
                </LineChart>
            </ResponsiveContainer>
        </CardContent>
       </Card>
    </div>
    
    {/* --- Modals --- */}
    <LogNutritionModal isOpen={activeModal === 'nutrition'} onClose={() => setActiveModal(null)} onLog={onAddNutritionLog} />

    <Modal isOpen={activeModal === 'goal'} onClose={() => setActiveModal(null)} title="Update Goal Progress">
        <div className="space-y-4">
            <div>
                <label className="block text-sm font-medium text-muted-foreground mb-1">Select Goal</label>
                <select value={goalId} onChange={e => setGoalId(e.target.value)} className="w-full bg-muted border-input rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-ring">
                    <option value="" disabled>Choose a goal...</option>
                    {activeGoals.map(g => <option key={g.id} value={g.id}>{g.title}</option>)}
                </select>
            </div>
            {goalId && <FormInput label={`New Progress (${goals.find(g=>g.id===goalId)?.metric})`} type="number" value={goalCurrent || ''} onChange={e => setGoalCurrent(Number(e.target.value))} />}
            <FormButton onClick={handleUpdateGoal}>Update Progress</FormButton>
        </div>
    </Modal>
    <Modal isOpen={activeModal === 'measurement'} onClose={() => setActiveModal(null)} title="Add Measurement">
        <div className="space-y-4">
            <FormInput label="Bodyweight (kg)" type="number" placeholder="e.g., 68.5" value={bodyweight || ''} onChange={e => setBodyweight(Number(e.target.value))} />
            <FormButton onClick={handleAddMeasurement}>Save Measurement</FormButton>
        </div>
    </Modal>
    </>
  );
};
