// src/pages/TrainerDashboard.vue
<template>
  <div class="space-y-6 pb-6">
    <!-- Header -->
    <div class="pt-6 px-6">
      <h1 class="text-3xl font-bold">Trainer Dashboard</h1>
      <p class="text-muted-foreground">Manage your clients and sessions</p>
    </div>

    <div class="px-6 space-y-6">
      <!-- Key Metrics -->
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <div class="p-4">
            <p class="text-sm text-muted-foreground mb-2">Total Clients</p>
            <p class="text-3xl font-bold">{{ clientsCount }}</p>
          </div>
        </Card>
        <Card>
          <div class="p-4">
            <p class="text-sm text-muted-foreground mb-2">Sessions This Week</p>
            <p class="text-3xl font-bold">{{ sessionsThisWeek }}</p>
          </div>
        </Card>
        <Card>
          <div class="p-4">
            <p class="text-sm text-muted-foreground mb-2">Total Workouts Logged</p>
            <p class="text-3xl font-bold">{{ workoutsCount }}</p>
          </div>
        </Card>
        <Card>
          <div class="p-4">
            <p class="text-sm text-muted-foreground mb-2">Unread Messages</p>
            <p class="text-3xl font-bold text-warning">{{ unreadChatsCount }}</p>
          </div>
        </Card>
      </div>

      <!-- Upcoming Sessions -->
      <Card v-if="upcomingSessions.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Upcoming Sessions</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="session in upcomingSessions.slice(0, 5)" :key="session.id" class="p-4">
            <div class="flex items-start justify-between">
              <div>
                <h3 class="font-semibold">{{ session.title }}</h3>
                <p class="text-sm text-muted-foreground">{{ formatSessionDate(session.date) }}</p>
                <p class="text-xs text-muted-foreground mt-1">📍 {{ session.location }} • {{ session.attendees.length
                  }}/{{ session.capacity }} registered</p>
              </div>
            </div>
          </div>
        </div>
      </Card>

      <!-- Recent Client Activity -->
      <Card v-if="recentWorkouts.length > 0">
        <div class="border-b border-border p-4">
          <h2 class="text-lg font-semibold">Recent Client Workouts</h2>
        </div>
        <div class="divide-y divide-border">
          <div v-for="workout in recentWorkouts.slice(0, 5)" :key="workout.id" class="p-4">
            <div class="flex items-start justify-between">
              <div>
                <p class="font-medium">{{ workout.exercises.length }} exercises completed</p>
                <p class="text-sm text-muted-foreground">{{ formatWorkoutDate(workout.date) }}</p>
              </div>
              <span :class="[
                'px-3 py-1 rounded text-xs font-medium',
                workout.completed ? 'bg-success/10 text-success' : 'bg-muted text-muted-foreground'
              ]">
                {{ workout.completed ? 'Completed' : 'In Progress' }}
              </span>
            </div>
          </div>
        </div>
      </Card>

      <!-- Quick Actions -->
      <div class="grid grid-cols-2 md:grid-cols-3 gap-4">
        <button
          class="p-4 rounded-lg border border-primary bg-primary/10 hover:bg-primary/20 transition-colors text-center">
          <UsersIcon class="w-6 h-6 mx-auto mb-2 text-primary" />
          <p class="font-medium text-sm">Manage Clients</p>
        </button>
        <button class="p-4 rounded-lg border border-muted hover:bg-muted transition-colors text-center">
          <CalendarIcon class="w-6 h-6 mx-auto mb-2 text-info" />
          <p class="font-medium text-sm">Schedule Session</p>
        </button>
        <button class="p-4 rounded-lg border border-muted hover:bg-muted transition-colors text-center">
          <MessageSquareIcon class="w-6 h-6 mx-auto mb-2 text-warning" />
          <p class="font-medium text-sm">Message Client</p>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import Card from '@/components/common/Card.vue';
import CalendarIcon from '@/components/icons/CalendarIcon.vue';
import MessageSquareIcon from '@/components/icons/MessageSquareIcon.vue';
import UsersIcon from '@/components/icons/UsersIcon.vue';
import { useUserStore } from '@/stores/user';
import type { Chat, Session, Workout } from '@/types';
import { formatDistanceToNow, isFuture, isThisWeek, parseISO } from 'date-fns';
import { computed, ref } from 'vue';

const userStore = useUserStore();
const currentUser = computed(() => userStore.currentUser);

// TODO: Replace with actual API calls
const sessions = ref<Session[]>([]);
const chats = ref<Chat[]>([]);
const workouts = ref<Workout[]>([]);

// Computed
const clientsCount = computed(() => {
  // Assuming attendees are clients
  const uniqueClients = new Set<string>();
  sessions.value.forEach(s => s.attendees.forEach(a => uniqueClients.add(a)));
  return uniqueClients.size;
});

const sessionsThisWeek = computed(() =>
  sessions.value.filter(s => isThisWeek(parseISO(s.date))).length
);

const workoutsCount = computed(() => workouts.value.length);

const unreadChatsCount = computed(() =>
  chats.value.filter(c => (c.unreadCount[currentUser.value?.id || ''] || 0) > 0).length
);

const upcomingSessions = computed(() =>
  sessions.value
    .filter(s => isFuture(parseISO(s.date)))
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
);

const recentWorkouts = computed(() =>
  workouts.value
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
);

// Methods
const formatSessionDate = (dateString: string) => {
  try {
    return formatDistanceToNow(parseISO(dateString), { addSuffix: true });
  } catch {
    return dateString;
  }
};

const formatWorkoutDate = (dateString: string) => {
  try {
    return formatDistanceToNow(parseISO(dateString), { addSuffix: true });
  } catch {
    return dateString;
  }
};
</script>

// react-legacy/components/TrainerDashboard.tsx

import React from 'react';
import { User, Session, Chat, Workout } from '../types';
import { Card, CardHeader, CardContent, CardTitle, CardDescription } from './common/Card';
import { CheckCircle2Icon, ChevronRightIcon, MessageSquareIcon, TrophyIcon, XCircleIcon } from './Icons';
import { users as allUsers } from '../data/mockData';
import { format, parseISO, isToday } from 'date-fns';

interface TrainerDashboardProps {
  currentUser: User;
  sessions: Session[];
  chats: Chat[];
  workouts: Workout[];
}

interface ClientCompliance {
    user: User;
    compliance: number;
    isLow: boolean;
}

export const TrainerDashboard: React.FC<TrainerDashboardProps> = ({ currentUser, sessions, chats, workouts }) => {
  
  const todaySessions = sessions.filter(s => isToday(parseISO(s.date)));
  const unreadDMs = chats.filter(c => c.unreadCount[currentUser.id] > 0);
  
  const recentPRs = workouts
    .flatMap(w => w.exercises.map(e => ({...e, userId: w.userId, workoutDate: w.date})))
    .filter(e => e.isPR)
    .sort((a,b) => new Date(b.workoutDate).getTime() - new Date(a.workoutDate).getTime())
    .slice(0, 5)
    .map(pr => ({
        ...pr,
        user: allUsers.find(u => u.id === pr.userId)
    }));

  // Mock compliance data
  const clientCompliance: ClientCompliance[] = allUsers
    .filter(u => u.role === 'CLIENT')
    .map((user, index) => {
        const compliance = [75, 55, 90][index % 3];
        return {
            user,
            compliance,
            isLow: compliance < 60
        }
    })
    .sort((a,b) => (a.isLow === b.isLow) ? 0 : a.isLow ? -1 : 1);

  return (
    <div className="space-y-6 p-4 md:p-6">
      <h1 className="text-2xl md:text-3xl font-bold text-foreground">
        Trainer Dashboard
      </h1>
      <p className="text-muted-foreground">Here's what's happening today, {currentUser.name.split(' ')[0]}.</p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card>
            <CardHeader>
                <CardTitle>Today's Sessions</CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-4xl font-bold">{todaySessions.length}</p>
                <p className="text-sm text-muted-foreground">sessions scheduled</p>
            </CardContent>
        </Card>
         <Card>
            <CardHeader>
                <CardTitle>Unread Messages</CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-4xl font-bold">{unreadDMs.length}</p>
                <p className="text-sm text-muted-foreground">conversations need attention</p>
            </CardContent>
        </Card>
         <Card>
            <CardHeader>
                <CardTitle>Low Compliance</CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-4xl font-bold">{clientCompliance.filter(c => c.isLow).length}</p>
                <p className="text-sm text-muted-foreground">clients to check in with</p>
            </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Upcoming Sessions</CardTitle>
            </CardHeader>
            <CardContent>
              {todaySessions.length > 0 ? (
                <ul className="space-y-4">
                  {todaySessions.map(session => (
                    <li key={session.id} className="flex items-center justify-between p-3 bg-muted rounded-lg">
                      <div>
                        <p className="font-semibold">{session.title}</p>
                        <p className="text-sm text-muted-foreground">
                          {format(parseISO(session.date), 'p')} - {session.location}
                        </p>
                      </div>
                       <ChevronRightIcon className="w-5 h-5 text-muted-foreground" />
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-sm text-muted-foreground text-center py-4">No sessions scheduled for today.</p>
              )}
            </CardContent>
          </Card>
          <Card>
             <CardHeader>
              <CardTitle>Client Compliance</CardTitle>
              <CardDescription>Workout & Nutrition logging adherence last 7 days.</CardDescription>
            </CardHeader>
            <CardContent>
                <ul className="space-y-3">
                    {clientCompliance.map(({user, compliance, isLow}) => (
                        <li key={user.id} className="flex items-center justify-between">
                            <div className="flex items-center space-x-3">
                                <img src={user.avatar} alt={user.name} className="w-10 h-10 rounded-full" />
                                <div>
                                    <p className="font-medium">{user.name}</p>
                                    <p className="text-xs text-muted-foreground">{user.email}</p>
                                </div>
                            </div>
                            <div className="flex items-center space-x-2">
                                <span className={`font-semibold ${isLow ? 'text-destructive' : 'text-green-500'}`}>{compliance}%</span>
                                {isLow ? <XCircleIcon className="w-5 h-5 text-destructive"/> : <CheckCircle2Icon className="w-5 h-5 text-green-500"/>}
                            </div>
                        </li>
                    ))}
                </ul>
            </CardContent>
          </Card>
        </div>
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Client Messages</CardTitle>
            </CardHeader>
            <CardContent>
                {unreadDMs.length > 0 ? (
                    <ul className="space-y-3">
                        {unreadDMs.map(chat => {
                            const client = allUsers.find(u => u.id !== currentUser.id && chat.participants.includes(u.id));
                            return (
                                <li key={chat.id} className="flex items-center justify-between p-2 hover:bg-muted rounded-md cursor-pointer">
                                    <div className="flex items-center space-x-3">
                                        <img src={client?.avatar} alt={client?.name} className="w-10 h-10 rounded-full" />
                                        <div>
                                            <p className="font-semibold text-sm">{client?.name}</p>
                                            <p className="text-xs text-muted-foreground truncate max-w-[150px]">{chat.lastMessage}</p>
                                        </div>
                                    </div>
                                    <div className="w-5 h-5 bg-primary text-primary-foreground text-xs font-bold rounded-full flex items-center justify-center">
                                        {chat.unreadCount[currentUser.id]}
                                    </div>
                                </li>
                            );
                        })}
                    </ul>
                ) : (
                    <p className="text-sm text-muted-foreground text-center py-4">All caught up!</p>
                )}
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>New PRs</CardTitle>
            </CardHeader>
            <CardContent>
                 {recentPRs.length > 0 ? (
                    <ul className="space-y-4">
                        {recentPRs.map(pr => (
                             <li key={pr.id} className="flex items-start space-x-3">
                                <TrophyIcon className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
                                <div>
                                    <p className="text-sm font-medium">{pr.user?.name}</p>
                                    <p className="text-sm text-muted-foreground">{pr.name}: <span className="font-semibold text-foreground">{pr.weight}kg</span> for {pr.reps} reps</p>
                                </div>
                            </li>
                        ))}
                    </ul>
                 ) : (
                    <p className="text-sm text-muted-foreground text-center py-4">No recent PRs.</p>
                 )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};
